cache:
 paths:
   - .m2/repository

stages: 
  - package 
  - deploy
  - s3
  
package: 
  stage: package
  script:
     - mvn -B package -DskipTests 
  artifacts: 
    paths: 
      - target
  image: maven
  
deploy:
  stage: deploy
  script: 
    - mvn -B -DaltDeploymentRepository=repo::default::file:./target/staging deploy -DskipTests 
    - cp target/arity-*-fat.jar target/staging/io/cloudonix/arity/*/
  artifacts: 
    paths:
      - target/staging
  image: maven
  
s3:
  stage: s3
  script: 
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  image: mesosphere/aws-cli
  only: 
    - master
    
s3snapshots:
  stage: s3
  script: 
    - s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/snapshots
  image: mesosphere/aws-cli
  only: 
    - develop
    
s3:
  stage: s3
  script: 
    - pip3 install awscli boto3
    - pip3 install pyyaml==4.2b4
    - pip3 install --no-deps awscli boto3
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  image: python
  only: 
    - master
    
  