variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/
  
stages: 
  - setup
  - package 
  - deploy
  - s3

offline-deps:
  stage: setup
  image: maven:3-jdk-9
  script:
    - '[ "$(($RANDOM%10))" == 0 ] && mvn -B -U dependency:go-offline || mvn -B dependency:go-offline'

package: 
  stage: package
  script:
     - mvn -B package -DskipTests -U
  artifacts: 
    paths: 
      - target
  image: maven:3-jdk-9
  
deploy:
  stage: deploy
  script: 
    - ls -la target || true
    - mvn -B -DaltDeploymentRepository=repo::default::file:./target/staging deploy -DskipTests 
    - cp target/arity-*-fat.jar target/staging/io/cloudonix/arity/*/
  artifacts:
    paths:
      - target/staging
  image: maven:3-jdk-9
  
s3:
  stage: s3
  script: 
    - pip install awscli
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  image: python:3.6.6-stretch
  only: 
    - master
 
s3-snapshots:
  stage: s3
  image:
    name: mesosphere/aws-cli
    entrypoint: [""]
  script: 
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/snapshots
  only: 
    - develop
