variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"
  
stages: 
  - package 
  - deploy
  - s3
  
package: 
  stage: package
  script:
     - mvn -B package -DskipTests -U
  artifacts: 
    paths: 
      - target
  image: maven:3-jdk-8
  
deploy:
  stage: deploy
  script: 
    - mvn -B -DaltDeploymentRepository=repo::default::file:./target/staging deploy -DskipTests 
    - cp target/arity-*-fat.jar target/staging/io/cloudonix/arity/*/
  artifacts: 
    paths:
      - target/staging
  image: maven:3-jdk-8
  
s3:
  stage: s3
  script: 
    - pip install awscli
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/releases
  image: python:3.6.6-stretch
  only: 
    - master
 
s3-snapshots:
  stage: s3
  image:
    name: mesosphere/aws-cli
    entrypoint: [""]
  script: 
    - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read ./target/staging/ s3://cloudonix-dist/maven2/snapshots
  only: 
    - develop
